---
# Gateway parameters
gateway_ip: "192.168.122.1"
gateway_ip_mask: "192.168.122.1/24"
broadcast_ip: "192.168.122.255"
gateway_interface: "br-vlan"

# Network parameters
external_network: "ext-net"

# Subnet parameters
subnet_name: "ext-subnet"
allocation_pool: "start=192.168.122.100,end=192.168.122.254"
subnet_cidr: "192.168.122.0/24"
