#!/bin/bash

INTERFACE=$1
ACTION=$4

if [[ $INTERFACE == "br_vlan" ]]; then
    if [[ $ACTION == "pre-up" ]]; then
        ip link add br_vlan-veth type veth peer name eth12 || true
        ip link set br_vlan-veth up
        ip link set eth12 up
        brctl addif br_vlan br_vlan-veth
    else
        brctl delif br_vlan br_vlan-veth
        ip link del br_vlan-veth || true
    fi
fi

