---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Debug variable gathering
    msg: "Ansible distribution is {{ ansible_distribution | lower}}, role_path is {{ role_path }}"

- debug: var=ansible_env.PWD

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths: vars
- name: make NFS directories
  file:
    dest: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - "/images"
    - "/volumes"
- name: configure NFS service
  lineinfile:
    dest: /etc/services
    state: present
    create: yes
    line: "nfs    2049/{{ item }}"
    regexp: "^[[:space:]]*nfs[[:space:]]*2049/{{ item }}"
  with_items:
    - "tcp"
    - "udp"
- name: configure NFS exports
  lineinfile:
    dest: /etc/exports
    state: present
    create: yes
    line: "{{ item }}"
  with_items:
    - "/images         *(rw,sync,no_subtree_check,no_root_squash)"
    - "/volumes        *(rw,sync,no_subtree_check,no_root_squash)"

- name: Install the NFS server package
  package:
    name: "{{ nfs_server_package }}"
    state: latest

- name: restart NFS service
  service:
    name: "{{ nfs_server_service }}"
    state: restarted
