---
sgabios_dir: /usr/share/sgabios/
libvirt_service_name: libvirtd
required_packages:
 - qemu-tools
 - qemu-kvm
 - qemu-x86
 - qemu-sgabios
 - libvirt
 - libvirt-client
 - libvirt-daemon
 - pkg-config
 - libvirt-devel
