---
- hosts: localhost
  connection: local
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf.yaml"
    - "vars/pdf.yaml"
  tasks:
    - name: Setup hosts
      shell: "openstack-ansible setup-hosts.yml"
      args:
        chdir: "{{ osa_path }}/playbooks/"
