---
- hosts: jumphost
  become: true
  vars_files:
    - "vars/defaults.yaml"
    - "vars/idf.yaml"
    - "vars/pdf.yaml"
  tasks:
    ##
    # Prepare inventory and config files
    ##
    - name: set bifrost inventory
      template:
        src: "templates/bifrost_inventory.json.j2"
        dest: "{{ bosa_config }}/bifrost_inventory.json"
    - name: set bifrost {{ item.name }} inventory
      template:
        src: "templates/bifrost_inventory.json.j2"
        dest: "{{ bosa_config }}/bifrost_inventory/{{ item.name }}.json"
      with_items: "{{ nodes }}"
    - name: get nodes ips
      set_fact:
        nodes_ip: >
          {{ nodes | node_ips (net_config['admin'].network, ip_shift) }}
    - name: get job nodes
      set_fact:
        role2nodes: "{{ xci.nodes_roles | role2nodes() }}"
    - name: prepare ssh config file
      template:
        src: "templates/ssh_config.j2"
        dest: "{{ ansible_env.HOME }}/.ssh/config"
    - name: prepare ssh root config file
      template:
        src: "templates/ssh_config.j2"
        dest: "/root/.ssh/config"
    - name: set ansible node inventory
      template:
        src: "templates/ansible_inventory.j2"
        dest: "{{ bosa_config }}/ansible_inventory"
    ##
    # Set various files
    ##
    - name: set .bash_aliases for bifrost
      copy:
        src: "files/bash_aliases"
        dest: "{{ ansible_env.HOME }}/.bash_aliases"
    ##
    # Check ipmi reachability
    ##
    - name: check ipmi reachability
      local_action:
        ping {{ item['remote_management']['address'] | regex_replace('/{d}*$')}}
      with_items: "{{ nodes }}"
    ##
    # Enroll
    ##
    - name: Enroll nodes
      shell:
        "bifrost-ansible -i inventory/bifrost_inventory.py enroll-dynamic.yaml"
      args:
        chdir: "{{ bifrost_path }}/playbooks/"
      environment:
        BIFROST_INVENTORY_SOURCE: "{{ bosa_config }}/bifrost_inventory.json"
    ##
    # Deploy
    ##
    - name: Deploy bifrost
      shell:
        "bifrost-ansible -i inventory/bifrost_inventory.py deploy-dynamic.yaml"
      args:
        chdir: "{{ bifrost_path }}/playbooks/"
      environment:
        BIFROST_INVENTORY_SOURCE: "{{ bosa_config }}/bifrost_inventory.json"
