---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - ../var/opnfv.yml
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
  roles:
    - role: remove-folders

- hosts: localhost
  connection: local
  vars_files:
    - ../var/opnfv.yml
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
  roles:
    - { role: clone-repository, project: "opnfv/releng-xci", repo: "{{ OPNFV_RELENG_GIT_URL }}", dest: "{{ OPNFV_RELENG_PATH }}", version: "{{ OPNFV_RELENG_VERSION }}" }

- hosts: localhost
  connection: local
  vars_files:
    - ../var/opnfv.yml
  tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
    - name: Synchronize local development releng-xci repository to XCI paths
      synchronize:
        src: "{{ OPNFV_RELENG_DEV_PATH }}"
        dest: "{{ OPNFV_RELENG_PATH }}"
        recursive: yes
        delete: yes
      when:
        - OPNFV_RELENG_DEV_PATH != ""
    - name: copy flavor inventory
      copy:
        src: "{{XCI_FLAVOR_ANSIBLE_FILE_PATH}}/inventory"
        dest: "{{OPNFV_RELENG_PATH}}/xci/playbooks"
