---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: localhost
  remote_user: root
  vars_files:
    - ../var/opnfv.yml
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
  roles:
    - { role: clone-repository, project: "opnfv/releng-xci", repo: "{{ OPNFV_RELENG_GIT_URL }}", dest: "{{ OPNFV_RELENG_PATH }}", version: "{{ OPNFV_RELENG_VERSION }}" }
      #- { role: clone-repository, project: "kubernetes-incubator/kubespray", repo: "{{ KUBESPRAY_GIT_URL }}", dest: "{{ KUBESPRAY_PATH }}", version: "{{ KUBESPRAY_VERSION }}" }
    - { role: clone-repository, project: "kubernetes-incubator/kubespray", repo: "https://github.com/kubernetes-incubator/kubespray.git", dest: "{{ XCI_DEVEL_ROOT }}/kubespray", version: "master" }

- hosts: localhost
  remote_user: root
  vars_files:
    - ../var/opnfv.yml
  tasks:
    - name: create opnfv_inventory directory (if needed)
      #shell: "/bin/mkdir -p {{ KUBESPRAY_PATH }}/opnfv_inventory"
      shell: "/bin/mkdir -p {{ XCI_DEVEL_ROOT }}/kubespray/opnfv_inventory"
    - name: copy kubespray inventory directory
      #shell: "/bin/cp -rf {{ OPNFV_RELENG_DEV_PATH }}/kubespray/inventory {{ KUBESPRAY_PATH }}/opnfv_inventory"
      shell: "/bin/cp -rf {{ OPNFV_RELENG_DEV_PATH }}/kubespray/inventory {{ XCI_DEVEL_ROOT }}/kubespray/opnfv_inventory"
      when:
        - OPNFV_RELENG_DEV_PATH != ""
