---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: opnfv
  remote_user: root
  vars_files:
    - ../var/opnfv.yml
  tasks:
    - name: install dbus and ptyhon-netaddr
      apt:
        name: "{{item}}"
        update_cache: yes
      with_items:
        - "python-netaddr"
        - "dbus"
