---
#
# This file is aimed to build the repo URL for ODL

- name: Set version 9 if ODL-master
  set_fact:
    repo_version: 9
  when:
    - ODL_VERSION == 'master'

- name: Set version 8 if ODL-oxygen
  set_fact:
    repo_version: 8
  when:
    - ODL_VERSION == 'oxygen'

- name: Set version 7 if ODL-nitrogen
  set_fact:
    repo_version: 7
  when:
    - ODL_VERSION == 'nitrogen'

- name: Generate the repo for Opensuse
  set_fact:
    generated_odl_repo: "https://git.opendaylight.org/gerrit/gitweb?p=integration/packaging.git;a=blob_plain;f=packages/rpm/example_repo_configs/opendaylight-{{ repo_version }}-opensuse-devel.repo"
  when:
    - ansible_pkg_mgr == 'zypper'

- name: Generate the repo for Centos
  set_fact:
    generated_odl_repo: "https://git.opendaylight.org/gerrit/gitweb?p=integration/packaging.git;a=blob_plain;f=packages/rpm/example_repo_configs/opendaylight-{{ repo_version }}-devel.repo"
  when:
    - ansible_pkg_mgr == 'yum'

- name: Generate the repo for Ubuntu
  set_fact:
    generated_odl_repo: "https://git.opendaylight.org/gerrit/gitweb?p=integration/packaging.git;a=blob_plain;f=packages/rpm/example_repo_configs/opendaylight-{{ repo_version }}-ubuntu-devel.repo"
  when:
    - ansible_pkg_mgr == 'apt'
