---
##
# Setup bifrost_inventory source
##
- name: clean bifrost detailled inventory folder
  file:
    path: "{{ bosa_config }}/bifrost_inventory/"
    state: absent
- name: set bifrost detailled inventory folder
  file:
    path: "{{ bosa_config }}/bifrost_inventory/"
    state: directory
- name: set bifrost inventory
  template:
    src: "templates/bifrost_inventory.json.j2"
    dest: "{{ bosa_config }}/bifrost_inventory.json"
- name: set bifrost {{ item.name }} inventory
  template:
    src: "templates/bifrost_inventory.json.j2"
    dest: "{{ bosa_config }}/bifrost_inventory/{{ item.name }}.json"
  with_items: "{{ nodes }}"
##
# Get facts related to nodes (ips, role)
##
- name: get nodes ips
  set_fact:
    nodes_ip: >
      {{ nodes | node_ips (net_config['admin'].network, ip_shift) }}
- name: get role of each nodes
  set_fact:
    role2nodes: "{{ xci.nodes_roles | role2nodes() }}"
##
# Prepare the ssh configs
##
- name: prepare ssh config file
  template:
    src: "templates/ssh_config.j2"
    dest: "{{ item }}"
  with_items:
    - "/root/.ssh/config"
    - "/home/{{ opnfv_user }}/.ssh/config"  # To update for multi-os
##
# Prepare ansible inventory for nodes_* roles
##
- name: set ansible nodes inventory
  template:
    src: "templates/ansible_inventory.j2"
    dest: "{{ bosa_config }}/ansible_inventory"
##
# Set .bash_aliases for a better ops life
##
- name: set .bash_aliases for bifrost
  copy:
    src: "files/bash_aliases"
    dest: "/home/{{ opnfv_user }}/.bash_aliases"
##
# Check ipmi reachability
##
- name: check ipmi reachability
  local_action:
    ping {{ item['remote_management']['address'] | regex_replace('/{d}*$')}}
  with_items: "{{ nodes }}"
##
# Enroll using prepared wrapper to ensure venv is used or not
##
- name: Enroll nodes
  shell:
    "bifrost-ansible -i inventory/bifrost_inventory.py enroll-dynamic.yaml"
  args:
    chdir: "{{ bifrost_path }}/playbooks/"
  environment:
    BIFROST_INVENTORY_SOURCE: "{{ bosa_config }}/bifrost_inventory.json"
##
# Deploy using prepared wrapper to ensure venv is used or not
##
- name: Deploy bifrost
  shell:
    "bifrost-ansible -i inventory/bifrost_inventory.py deploy-dynamic.yaml"
  args:
    chdir: "{{ bifrost_path }}/playbooks/"
  environment:
    BIFROST_INVENTORY_SOURCE: "{{ bosa_config }}/bifrost_inventory.json"
