#!/bin/bash

if [[ $OPNFV_SCENARIO == "os-odl-nofeature" ]] && [[ $XCI_FLAVOR == "ha" ]]; then
    export VM_MEMORY_SIZE=20480
elif [[ $OPNFV_SCENARIO == "os-odl-nofeature" ]]; then
    export VM_MEMORY_SIZE=16384
fi