---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 Orange and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: "Start XCI hosts"
  become: "yes"
  virt:
    name: "{{ idf.xci.pod_name }}_{{ node.name }}"
    state: running

- name: wait ssh to be reachable
  shell: >
    ssh -o StrictHostKeyChecking=no
    {{xci_hosts_user}}@{{ ip }} python --version
  vars:
    ip: "{{ nodes_net_config[node.name][idf.xci.pxe_network]['ip'] }}"
  register: ping_ssh
  until: ping_ssh.rc == 0
  retries: 24
  delay: 5
  when: "True"
  tags:
    - skip_ansible_lint

- name: update ssh known hosts
  shell: >
    ssh-keygen -f "{{ known_hosts_file }}" -R {{ ip }};
    ssh-keyscan -t rsa {{ ip }} >> {{ known_hosts_file }};
    ssh {{xci_hosts_user}}@{{ ip }} hostname
  vars:
    known_hosts_file: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
    ip: "{{ nodes_net_config[node.name][idf.xci.pxe_network]['ip'] }}"
  tags:
    - skip_ansible_lint
