---
- name: Write new resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Make resolv.conf immutable
  shell: "chattr +i /etc/resolv.conf"
  changed_when: false
  args:
    executable: /bin/bash
  tags:
    - skip_ansible_lint

#This rule allows openstack client in OPNFV VM to reach openstack
- name: Update routing table with kube service addresses
  shell: "ip route add {{ kube_service_addresses }} via 192.168.122.3 dev br-vlan onlink"
  changed_when: false
  args:
    executable: /bin/bash
  tags:
    - skip_ansible_lint

