---
- name: Install packages in kubernetes nodes
  package:
    name: "{{ packages }}"
    state: present
  changed_when: false
  vars:
    packages:
    - ceph-common
    - rbd-nbd
    - apparmor
    - nfs-common

- name: Add entry for ceph in hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[inventory_hostname].ip }} ceph-mon.ceph.svc.cluster.local"
