---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
proxy_values:
  HTTP_PROXY: "{{  lookup('env','http_proxy') }}"
  HTTPS_PROXY: "{{  lookup('env','https_proxy') }}"
  NO_PROXY: "{{  lookup('env','no_proxy') }}"
