- name: Create patch to get correct clouds.yaml file
  copy:
    dest: "/tmp/080-keystone.sh.patch"
    content: |
      --- 080-keystone.sh.old	2019-04-23 14:16:19.099639355 +0300
      +++ 080-keystone.sh	2019-04-23 14:17:00.055637659 +0300
      @@ -34,4 +34,5 @@
       helm status keystone
       export OS_CLOUD=openstack_helm
       sleep 30 #NOTE(portdirect): Wait for ingress controller to update rules and restart Nginx
      +cp /etc/openstack/clouds.yaml .
       openstack endpoint list
    mode: 0644

- name: Create patch to correct validation stack dns sever
  copy:
    dest: "/tmp/heat-public-net-deployment.yaml.patch"
    content: |
      --- heat-public-net-deployment.yaml.old	2019-04-25 08:19:33.202181094 +0000
      +++ heat-public-net-deployment.yaml	2019-04-25 08:25:15.825539349 +0000
      @@ -45,4 +45,4 @@
               get_param: subnet_gateway
             enable_dhcp: false
             dns_nameservers:
      -        - 10.96.0.10
      +        - 10.233.0.3
  mode: 0644

- name: Apply the patches
  patch:
    src: "/tmp/{{ item.source }}.patch"
    dest: "/root/repos/openstack-helm/{{ item.path }}/{{ item.name }}"
    remote_src: yes
  with_items:
    - { source: "080-keystone.sh", name: "080-keystone.sh", path: "tools/deployment/developer/common" }
    - { source: "heat-public-net-deployment.yaml", name: "heat-public-net-deployment.yaml", path: "tools/gate/files" }

