---
# defaults file for bifrost-create-vm-nodes
baremetal_json_file: '/tmp/baremetal.json'

# We collect these parameters from the pdf
vm_nic: "virtio"
vm_groups: {}
vm_default_groups: "{{ lookup('env', 'DEFAULT_HOST_GROUPS').split() | default(['baremetal'], true) }}"
vm_disk_cache: unsafe
node_names: "{{ lookup('env', 'NODE_NAMES').split() }}"

network_bridge_pxe: 'br-pxe'
network_bridge_mgmt: 'br-mgmt'

network_interface_pxe_mac: "{{ jumphost.interfaces[idf.net_config.pxe.interface].mac_address }}"
network_interface_pxe_vlan: "{{ jumphost.interfaces[idf.net_config.pxe.interface].vlan }}"
network_interface_pxe: >-
  {% for x in (ansible_interfaces | map('regex_replace', '-', '_') | map('regex_replace', '^', 'ansible_') | map('extract', hostvars[inventory_hostname]) |  selectattr('macaddress','defined')) -%}
  {% if x.macaddress == network_interface_pxe_mac %}
  {{ x.device }}
  {%- endif %}
  {%- endfor %}

network_interface_mgmt_mac: "{{ jumphost.interfaces[idf.net_config.admin.interface].mac_address }}"
network_interface_mgmt_vlan: "{{ jumphost.interfaces[idf.net_config.admin.interface].vlan }}"

#TODO ASK MARKOS HOW TO SELECT THE RIGHT ONE ==>     "network_interface_mgmt": "  br-external ens1f0 ens1f0.84"
network_interface_mgmt: 'ens1f0'
#network_interface_mgmt: >-
#  {% set interfaces = [] %}
#  {% for x in (ansible_interfaces | map('regex_replace', '-', '_') | map('regex_replace', '^', 'ansible_') | map('extract', hostvars[inventory_hostname]) |  selectattr('macaddress','defined')) -%}
#  {% if x.macaddress == network_interface_mgmt_mac %}
#  {{ x.device }}
#  {%- endif %}
#  {%- endfor %}


vm_network_pxe: "{{ lookup('env', 'VM_NET_BRIDGE') | default('pxe', true) }}"
vm_network_mgmt: "{{ lookup('env', 'VM_NET_BRIDGE_MGMT') | default('mgmt', true) }}"

node_network_netmask: "255.255.255.0"

node_storage_pool: "{{ lookup('env', 'LIBVIRT_STORAGE_POOL') | default('default', true) }}"
node_storage_pool_path: "/var/lib/libvirt/images"
node_logdir: "/var/log/libvirt/baremetal_logs"
# NOTE(pas-ha) next two are generic values for most OSes, overridden by distro-specifc vars
vm_emulator: "/usr/bin/qemu-system-x86_64"
# NOTE(pas-ha) not really tested with non-local qemu connections
vm_libvirt_uri: "{{ lookup('env', 'LIBVIRT_CONNECT_URI') | default('qemu:///system', true) }}"

opnfv_image_path: "/var/lib/libvirt/images"
