---
# defaults file for bifrost-create-vm-nodes
baremetal_json_file: '/tmp/baremetal.json'

# We collect these parameters from the pdf
vm_nic: "virtio"
vm_groups: {}
vm_default_groups: "{{ lookup('env', 'DEFAULT_HOST_GROUPS').split() | default(['baremetal'], true) }}"
vm_disk_cache: "{{ lookup('env', 'VM_DISK_CACHE') | default('unsafe', true) }}"
node_names: "{{ lookup('env', 'NODE_NAMES').split() }}"

# NOTE(pas-ha) name and default are chosen to be the same
# as in 'bifrost-ironic-install' role
network_interface_pxe: "{{ idf.osa.jumphost.bridges.pxe | default('br-pxe', true) }}"
network_interface_mgmt: "{{ idf.osa.jumphost.bridges.mgmt | default('br-mgmt', true) }}"
# NOTE(pas-ha) these correspond to settings for the libvirt network created by default
vm_network_pxe: "{{ lookup('env', 'VM_NET_PXE_BRIDGE') | default('pxe', true) }}"
vm_network_mgmt: "{{ lookup('env', 'VM_NET_MGMT_BRIDGE') | default('mgmt', true) }}"
node_network_netmask: "255.255.255.0"

node_storage_pool: "{{ lookup('env', 'LIBVIRT_STORAGE_POOL') | default('default', true) }}"
node_storage_pool_path: "/var/lib/libvirt/images"
node_logdir: "/var/log/libvirt/baremetal_logs"
# NOTE(pas-ha) next two are generic values for most OSes, overridden by distro-specifc vars
vm_emulator: "/usr/bin/qemu-system-x86_64"
# NOTE(pas-ha) not really tested with non-local qemu connections
vm_libvirt_uri: "{{ lookup('env', 'LIBVIRT_CONNECT_URI') | default('qemu:///system', true) }}"

opnfv_image_path: "/var/lib/libvirt/images"
