---
- name: Remove list of packages
  apt:
    name: "{{item}}"
    update_cache: 'yes'
    state: absent
  with_items:
    - python-six
- name: Install list of packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python-pip
    - python-dev
    - libssl-dev
    - virtualenv
    - git
