---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2018 Orange and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Install Debian packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    "{{ pkg_required.debian }}"
  when: ansible_distribution == 'Debian'
        or ansible_distribution == 'Ubuntu'

- name: install RHEL or CentOS packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    "{{ pkg_required.rh }}"
  when: ansible_distribution == 'RHEL'
        or ansible_distribution == 'CentOS'

- name: install Suse packages
  zypper:
    name: "{{item}}"
    state: present
  with_items:
    "{{ pkg_required.suse }}"
  when: ansible_os_family | lower == "suse"

- name: upgrade pip
  pip:
    name: pip
    state: latest
  tags:
    - skip_ansible_lint

- name: install pip packages
  pip:
    name: "{{item}}"
    state: present
  with_items:
    "{{ pkg_required.pip }}"

##
# setup wrappers for an easier remote run
##
- name: Set wrappers
  become: true
  template:
    dest: "/usr/local/bin/{{ item }}"
    src: "templates/{{ item }}.j2"
    mode: 0555
  with_items:
    - bifrost-ansible
    - bifrost-ironic
