---

##
# install bifrost
##

# David - move to servers-deploy.sh
# - name: Install bifrost
#   shell: >
#     bifrost-ansible -i inventory/target install.yaml
#     -e staging_drivers_include=true;
#   args:
#     chdir: "{{ bifrost_src_folder }}/playbooks/"
#   when: "True"
# Upgrade pyasn1 as it make ironic conductor fail
# "hardware type or interface pxe_ilo could not be loaded"
- name: Upgrade pyasn1 for bifrost
  # become: true
  pip:
    name: pyasn1
    virtualenv: "{{ bifrost_venv_folder }}"

- name: restart ironic-conductor
  service:
    name: ironic-conductor
    state: restarted

##
# update dnsmasq
##
- name: correct dnsmasq config - default gateway
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^dhcp-option=3'
    line: "dhcp-option=3,{{ net_config[idf.xci.pxe_network].gateway }}"
- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
