---
# Copyright 2017, SUSE LINUX GmbH.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
- name: Fetch info from neutron
  hosts: opendaylight
  user: root
  tasks:
    - name: Fetch the ml2_conf.ini to process ODL variables
      fetch:
        src: "/etc/neutron/plugins/ml2/ml2_conf.ini"
        dest: "/tmp/ml2_conf.ini"
        flat: yes


- name: check filesystem
  hosts: localhost
  connection: local
  command: "ls /home"
  register: outputls

- debug: var=outputls


- name: check filesystem2
  hosts: localhost
  connection: local
  command: "ls /home/devuser/releng-xci"
  register: outputls2

- debug: var=outputls2


- name: check filesystem3
  hosts: localhost
  connection: local
  command: "ls /home/devuser/releng-xci/.cache/repos/"
  register: outputls3

- debug: var=outputls3


- name: check filesystem4
  hosts: localhost
  connection: local
  command: "ls /home/devuser/releng-xci/.cache/repos/openstack-ansible/inventory"
  register: outputls4

- debug: var=outputls4

- name: check inventory
  hosts: localhost
  connection: local
  command: "python /home/devuser/releng-xci/.cache/repos/openstack-ansible/inventory/dynamic_inventory.py"
  register: outputpython

- debug: var=outputpython


- name: Prepare the environment for testing
  hosts: opnfv
  user: root
  vars_files:
    - ../var/opnfv.yml
    - ../installer/osa/files/openstack_services.yml
  roles:
    - role: "prepare-tests"
