---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  vars_files:
    - ../var/opnfv.yml
  roles:
    - role: remove-folders

- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../var/opnfv.yml
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
  roles:
    - { role: clone-repository, project: "opnfv/releng-xci", repo: "{{ OPNFV_RELENG_GIT_URL }}", dest: "{{ OPNFV_RELENG_PATH }}", version: "{{ OPNFV_RELENG_VERSION }}" }
    - { role: clone-repository, project: "opnfv/bifrost", repo: "{{ OPENSTACK_BIFROST_GIT_URL }}", dest: "{{ OPENSTACK_BIFROST_PATH }}", version: "{{ OPENSTACK_BIFROST_VERSION }}" }

  tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
    - name: Synchronize local development bifrost repository to XCI paths
      # command module is much faster than the copy module
      synchronize:
        src: "{{ OPENSTACK_BIFROST_DEV_PATH }}"
        dest: "{{ OPENSTACK_BIFROST_PATH }}"
        recursive: yes
        delete: yes
      when:
        - OPENSTACK_BIFROST_DEV_PATH != ""
    - name: Synchronize local development releng-xci repository to XCI paths
      synchronize:
        src: "{{ OPNFV_RELENG_DEV_PATH }}"
        dest: "{{ OPNFV_RELENG_PATH }}"
        recursive: yes
        delete: yes
      when:
        - OPNFV_RELENG_DEV_PATH != ""
    - name: Copy extra vars to releng-xci and bifrost
      synchronize:
        src: "{{ XCI_EXTRA_VARS_PATH }}"
        dest: "{{ item }}"
      with_items:
        - "{{ OPNFV_RELENG_PATH }}/xci/playbooks"
        - "{{ OPENSTACK_BIFROST_PATH }}/playbooks/inventory"
      when:
        - XCI_EXTRA_VARS_PATH != ""
    - name: combine opnfv/releng-xci and openstack/bifrost scripts/playbooks
      copy:
        src: "{{ OPNFV_RELENG_PATH }}/bifrost/"
        dest: "{{ OPENSTACK_BIFROST_PATH }}"
