---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
- hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../var/opnfv.yml
  pre_tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
  roles:
    - role: clone-repository
      project: "opnfv/bifrost"
      repo: "{{ OPENSTACK_BIFROST_GIT_URL }}"
      dest: "{{ XCI_CACHE }}/repos/bifrost"
      version: "{{ OPENSTACK_BIFROST_VERSION }}"

  tasks:
    - name: Load distribution variables
      include_vars:
        file: ../var/{{ ansible_os_family }}.yml
    - name: Synchronize local development bifrost repository to XCI paths
      # command module is much faster than the copy module
      synchronize:
        src: "{{ OPENSTACK_BIFROST_DEV_PATH }}"
        dest: "{{ XCI_CACHE }}/repos/bifrost"
        recursive: yes
        delete: yes
      when:
        - OPENSTACK_BIFROST_DEV_PATH != ""
    - name: combine opnfv/releng-xci and openstack/bifrost scripts/playbooks
      copy:
        src: "{{ XCI_PATH}}/bifrost/"
        dest: "{{ XCI_CACHE }}/repos/bifrost"
