---
- hosts: opnfv
  remote_user: root
  vars_files:
    - "{{ xci_path }}/xci/var/opnfv.yml"

  tasks:
    - name: Set kubernetes service account permissions
      command: "kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default"
      changed_when: false

    - name: Set kubernetes node labels
      command: "kubectl label nodes {{ item }} --all"
      changed_when: false
      with_items:
        - openstack-control-plane=enabled
        - openstack-compute-node=enabled
        - openstack-helm-node-class=primary
        - openvswitch=enabled
        - linuxbridge=enabled
        - ceph-mon=enabled
        - ceph-osd=enabled
        - ceph-mds=enabled
        - ceph-mgr=enabled
        - ceph-rgw=enabled

    - name: Create directories
      file:
        path: /root/{{ item }}
        state: directory
      with_items:
        ['repos','tmp', '.helm/repository/local']

    - name: Clone openstack-helm
      git:
        repo: "{{ osh_git_url }}"
        dest: /root/repos/openstack-helm
        version: "{{ osh_version }}"
        update: true
        force: true
      register: git_clone
      until: git_clone is success
      retries: 2
      delay: 5

    - name: Clone openstack-helm-infra
      git:
        repo: "{{ osh_infra_git_url }}"
        dest: /root/repos/openstack-helm-infra
        version: "{{ osh_infra_version }}"
        update: true
        force: true
      register: git_clone
      until: git_clone is success
      retries: 2
      delay: 5

    - name: Get helm
      get_url:
        url: "{{ osh_helm_binary_url }}/helm-{{ osh_helm_binary_version }}-linux-amd64.tar.gz"
        dest: tmp

    - name: Uncompress helm package
      command: "tar zxvf  tmp/helm-{{ osh_helm_binary_version }}-linux-amd64.tar.gz --strip-components=1 -C tmp/"
      changed_when: false
      tags:
        - skip_ansible_lint

    - name: Put helm in system binaries
      copy:
        src: tmp/helm
        dest: /usr/bin/helm
        remote_src: yes
        mode: 0755

    - name: Create helm-serve service file
      copy:
        dest: "/etc/systemd/system/helm-serve.service"
        content: |
          [Unit]
          Description=Helm Server
          After=network.target
          [Service]
          User=root
          Restart=always
          ExecStart=/usr/bin/helm serve
          [Install]
          WantedBy=multi-user.target
        mode: 0640

    - name: Start helm-serve service
      service:
        name: helm-serve
        state: started
        enabled: yes

    - name: Wait for helm-serve service to start
      wait_for:
        port: 8879
        host: 127.0.0.1

    - name: Install pyhelm
      pip:
        name: pyhelm

    - name: Init helm
      command: "helm init"
      changed_when: false

    - name: Remove stable (external) service from helm
      command: "helm repo remove stable"
      changed_when: false

    - name: Add local repositories service to helm
      command: "helm repo add local http://localhost:8879/charts"
      changed_when: false

    - name: Make charts from infra
      make:
        chdir: /root/repos/openstack-helm-infra
        target: "{{ item }}"
      with_items:
        - helm-toolkit
        - ingress
        - mariadb
        - rabbitmq
        - memcached
        - ceph-mon
        - ceph-osd
        - ceph-client
        - ceph-provisioners
        - ceph-rgw
        - openvswitch
        - libvirt

    - name: Install packages
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - patch
        - ipcalc
        - jq

    - name: Install packages in kubernetes nodes
      package:
        name: "{{ packages }}"
        state: present
      changed_when: false
      vars:
        packages:
        - ceph-common
        - rbd-nbd
        - apparmor
      delegate_to: "{{ item }}"
      with_items:
        - "192.168.122.3"
        - "192.168.122.4"
        - "192.168.122.5"

    - name: Create patch to get correct clouds.yaml file
      copy:
        dest: "/tmp/080-keystone.sh.patch"
        content: |
          --- 080-keystone.sh.old	2019-06-03 14:17:52.113385809 +0300
          +++ 080-keystone.sh	2019-06-03 14:18:33.969386706 +0300
          @@ -30,6 +30,7 @@
           helm status keystone
           export OS_CLOUD=openstack_helm
           sleep 30 #NOTE(portdirect): Wait for ingress controller to update rules and restart Nginx
          +cp /etc/openstack/clouds.yaml .
           openstack endpoint list
           # Delete the test pod if it still exists
           kubectl delete pods -l application=keystone,release_group=keystone,component=test --namespace=openstack --ignore-not-found
        mode: 0644

    - name: Create patch to fix a missing tempest image and cloud parameters
      copy:
        dest: "/tmp/tempest-values.yaml.patch"
        content: |
          --- values.yaml.old	2019-06-03 14:24:39.489394544 +0300
          +++ values.yaml	2019-06-03 14:25:26.813395559 +0300
          @@ -145,7 +145,7 @@
                 container_formats: bare
                 disk_formats: raw
               network:
          -      dns_servers: 10.96.0.10
          +      dns_servers: 10.233.0.3
                 project_networks_reachable: false
                 shared_physical_network: true
               network-feature-enabled:
      mode: 0644

    - name: Apply the patches
      patch:
        src: "/tmp/{{ item.source }}.patch"
        dest: "/root/repos/openstack-helm/{{ item.path }}/{{ item.name }}"
        remote_src: yes
      with_items:
        - { source: "080-keystone.sh", name: "080-keystone.sh", path: "tools/deployment/multinode" }
        - { source: "tempest-values.yaml", name: "values.yaml", path: "tempest" }

    - name: Modify resolv.conf file and create route to DNS patch
      copy:
        dest: "/root/repos/openstack-helm-infra/route_to_dns.sh"
        content: |
          #!/bin/bash
          kube_service_addresses=$(grep -r 'kube_service_addresses:' /root/releng-xci/.cache/repos/kubespray/opnfv_inventory/group_vars/k8s-cluster.yml | sed -e 's/kube_service_addresses: //')
          echo $kube_service_addresses
          ip route add $kube_service_addresses via 192.168.122.3 dev br-vlan onlink
          ip_route=$(ip r)
          echo $ip_route
          cat > /etc/resolv.conf <<EOF
          search svc.cluster.local cluster.local
          nameserver 10.233.0.3
          nameserver 192.168.122.1
          EOF
          chattr +i /etc/resolv.conf
          sed -i 's/10.96.0.10/10.233.0.3/gi' /root/repos/openstack-helm-infra/kube-dns/values.yaml
        mode: 0755

    - name: Apply route_to_dns patch
      command: ./route_to_dns.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm-infra

# These tasks call OSH installation shell scripts

    - name: Setup Clients
      command: ./tools/deployment/multinode/010-setup-client.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy the ingress controller
      command: ./tools/deployment/multinode/020-ingress.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Ceph
      command: ./tools/deployment/multinode/030-ceph.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Activate the openstack namespace to be able to use Ceph
      command: ./tools/deployment/multinode/040-ceph-ns-activate.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy MariaDB
      command: ./tools/deployment/multinode/050-mariadb.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy RabbitMQ
      command: ./tools/deployment/multinode/060-rabbitmq.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy memcached
      command: ./tools/deployment/multinode/070-memcached.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Keystone
      command: ./tools/deployment/multinode/080-keystone.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Rados Gateway for object store
      command: ./tools/deployment/multinode/090-ceph-radosgateway.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Glance
      command: ./tools/deployment/multinode/100-glance.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Cinder
      command: ./tools/deployment/multinode/110-cinder.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy OpenvSwitch
      command: ./tools/deployment/multinode/120-openvswitch.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Libvirt
      command: ./tools/deployment/multinode/130-libvirt.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Compute Kit (Nova and Neutron)
      command: ./tools/deployment/multinode/140-compute-kit.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Heat
      command: ./tools/deployment/multinode/150-heat.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

    - name: Deploy Barbican
      command: ./tools/deployment/multinode/160-barbican.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm

# Deployment validation
    - name: Deploy tempest
      command: ./tools/deployment/multinode/900-tempest.sh
      changed_when: false
      args:
        chdir: /root/repos/openstack-helm
