---

- name: copy quagga variable file
  copy:
    src: openstack-ansible/pike/group-vars/quagga_all.yml
    dest: "{{openstack_osa_path}}/group-vars/quagga_all.yml"

- name: Add the Quagga configuration playbook
  copy:
    src: openstack-ansible/pike/playbooks/os-setup-bgp-odl.yml
    dest: "{{openstack_osa_path}}/playbooks/os-setup-bgp-odl.yml"

- name: copy OPNFV role requirements
  copy:
    src: "ansible-role-requirements-pike.yml"
    dest: "{{openstack_osa_path}}/ansible-role-requirements.yml"
