---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2017-18 Ericsson AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: copy user_variables_os-odl-bgpvpn.yml
  copy:
    src: "user_variables_os-odl-bgpvpn.yml"
    dest: "{{openstack_osa_etc_path}}/user_variables_os-odl-bgpvpn.yml"

- name: copy user_variables_os-odl-bgpvpn-ha.yml
  copy:
    src: "{{xci_flavor}}/user_variables_os-odl-bgpvpn-ha.yml"
    dest: "{{openstack_osa_etc_path}}/user_variables_os-odl-bgpvpn-ha.yml"
  when:
  - xci_flavor == "ha"

- name: copy os-odl-bgpvpn scenario specific openstack_user_config.yml
  copy:
    src: "{{xci_flavor}}/openstack_user_config.yml"
    dest: "{{openstack_osa_etc_path}}/openstack_user_config.yml"

- name: copy os-odl-bgpvpn scenario specific setup-openstack.yml
  copy:
    src: "setup-openstack.yml"
    dest: "{{openstack_osa_path}}/playbooks"

- name: Copy the OSA not-yet-upstreamed files for Pike
  include: add-osa-files-pike.yml
  when: openstack_osa_version == "stable/pike"

- name: Copy the OSA not-yet-upstreamed inventory files for Pike
  include: add-inventory-files-pike.yml
  when: openstack_osa_version == "stable/pike"
