#- name: Stop neutron-openvswitch-agent service
#  service:
#    name: neutron-openvswitch-agent
#    state: stopped
#  when:
#   - inventory_hostname in groups["neutron_openvswitch_agent"]
   

#- name: Change the bridge mappings for the external network
#  ini_file: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini section=ovs option=bridge_mappings value=flat:br-ex
#  when:
#   - inventory_hostname in groups["neutron_openvswitch_agent"]
#   - inventory_hostname in groups["compute_hosts"]

#- name: Remove bridge mappings in compute hosts only
#  ini_file: dest=/etc/neutron/plugins/ml2/openvswitch_agent.ini section=ovs option=bridge_mappings state=absent
#  when:
#   - inventory_hostname in groups["neutron_openvswitch_agent"]
#   - inventory_hostname not in groups["network_hosts"]


#- name: Add bridge for the external network
#  openvswitch_bridge:
#    bridge: br-ex
#    state: present
#  when:
#   - inventory_hostname in groups["neutron_agents_container"]
#   - inventory_hostname not in groups["compute_hosts"]

#- name: Add port to br-ex
#  openvswitch_port:
#    bridge: br-ex
#    port: "eth12"
#    state: present
#  notify:
#    - Restart neutron services
#  when:
#   - inventory_hostname in groups["neutron_agents_container"]
#   - inventory_hostname not in groups["compute_hosts"]

- name: Restart openvswitch service
  service:
    name: openvswitch-switch
    state: restarted
  when:
   - inventory_hostname in groups["neutron_agents_container"]

