---
# SPDX-license-identifier: Apache-2.0
#

- hosts: jumphost
  gather_facts: true
  vars_files:
    - var/opnfv.yml
    - var/pdf.yml
    - var/idf.yml
    - var/xci_hosts.yml
  roles:
    - role: vm-management
      vars:
        deploy_size: "{{ XCI_FLAVOR }}"
        xci_root: "/opt/xci/{{ xci.pod_name }}"
        xci_hosts_image: "{{ xci_hosts_images[XCI_DISTRO|lower()]}}"
